version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=storefront.settings
    volumes:
      - static-data:/app/staticfiles
      - media-data:/app/mediafiles
    networks:
      - meowmart_net
    command: python manage.py runserver 0.0.0.0:9000

  proxy:
    build:
      context: ./docker/proxy
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - static-data:/vol/static
      - media-data:/vol/media
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - meowmart_net

volumes:
  static-data:
  media-data:


networks:
  meowmart_net:
